### ISSUE TITLE
React Icon Gets Cutoff When Hovering on Firefox 

### ISSUE THREAD

**Issue by ahilashsasidharan** [a-knaw-knee-mus/Portfolio-NextJS#1]
#### Description
It seems that when viewing your website on the Firefox web browser the react icon does not zoom correctly on hover, and is cutoff at the top. 

#### Pictures 
![image](https://user-images.githubusercontent.com/79016853/185647598-725ae2ee-640d-4232-b659-d392f2f6fd2a.png)

**Comment by a-knaw-knee-mus** [comment]
Have you tried using Edge? I believe the issue is resolved there :)

**Comment by ahilashsasidharan** [comment]
@a-knaw-knee-mus hey I actually don't use chromium based browsers. Would it be possible to look into this and reopen the issue as I don't believe this is fixed.

**Comment by a-knaw-knee-mus** [comment]
Unfortunately, I am swamped with work and do not have the capacity to do it. Please check the source code and if you have a fix please open a pull request. Take care!

**Comment by ahilashsasidharan** [comment]
@a-knaw-knee-mus Alright I will look into this. Kudos Friend! Is it possible to reopen the issue so those interested could look into it?

**Comment by a-knaw-knee-mus** [comment]
Hey @ahilashsasidharan I recently heard from my peers that you are working on a riipen. I believe it would be in your best interest to prioritize. Once I have confirmation of your completion I would gladly reopen this issue.
