### ISSUE TITLE
Project Card Readability 

### ISSUE THREAD

**Issue by eldossjogy** [a-knaw-knee-mus/Portfolio-NextJS#2]
The last two project cards have text that is unreadable. Please make the necessary changes to make them readable. Attached is an example of the issue.
![image](https://user-images.githubusercontent.com/77898541/185815352-5d42c2eb-a732-4e99-8111-1a3a5d2fca07.png)

**Comment by a-knaw-knee-mus** [comment]
Hi, thank you for bringing this to my attention. I took a look and it seems to be because the text in my Sanity.io backend was not recognized as bullet points so the necessary styles were not added. Should be fixed now. 👍
