### ISSUE TITLE
SEO keywords do not work

### ISSUE THREAD

**Issue by ryanch117** [a-knaw-knee-mus/Portfolio-NextJS#3]
Hello Mr. Mehdi Ali,

When I was looking for your website through the 'Google' search engine, I was unable to locate it by using certain keywords such as 'portfolio' and 'tailwind CSS'. I was wondering if you could fix this, as I really want to be able to find your website using the aforementioned keywords.  Thanks :D

**Comment by a-knaw-knee-mus** [comment]
Hello ryanch117 (nice name :D), I have actually been looking into this issue myself so I'm surprised you brought this up (what a coincidence)! Unfortunately, I have not found a fix as of yet but I believe it has to do with the keywords meta tag 🤔, and even worse news 😱 is that I'm swamped atm (at the moment) 😞 so I can't invest time ⌛ into this for now. If you have any proposed 💍 solutions please open a PR and I'll check ✔️ it out 😄. Ttyl (talk to you later)!

**Comment by ryanch117** [comment]
@a-knaw-knee-mus Thank you for your time and consideration!!! 👯‍♂️

**Comment by a-knaw-knee-mus** [comment]
For you? Anything! 🤝
